"""init db

Revision ID: 11e18054647a
Revises: 
Create Date: 2026-07-14 03:10:01.158745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e18054647a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('string_value', sa.String(length=255), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('integer_value', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('list_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'field_id', name='uq_record_field')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_values')
    op.drop_table('records')
    op.drop_table('fields')
    # ### end Alembic commands ###
