"""init db

Revision ID: e9c9d829a00a
Revises: 
Create Date: 2026-07-14 13:41:07.416843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c9d829a00a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('field_id')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_key'), ['key'], unique=True)

    op.create_table('record_values',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('string_value', sa.String(length=255), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('integer_value', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('list_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.PrimaryKeyConstraint('record_id', 'field_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_values')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_key'))

    op.drop_table('fields')
    # ### end Alembic commands ###
